# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_about(object):
    def setupUi(self, about):
        about.setObjectName("about")
        about.resize(607, 273)
        about.setMinimumSize(QtCore.QSize(607, 0))
        about.setMaximumSize(QtCore.QSize(607, 16777215))
        self.aboutbg = QtWidgets.QLabel(about)
        self.aboutbg.setGeometry(QtCore.QRect(0, 0, 611, 431))
        self.aboutbg.setMinimumSize(QtCore.QSize(611, 0))
        self.aboutbg.setMaximumSize(QtCore.QSize(611, 16777215))
        self.aboutbg.setText("")
        self.aboutbg.setPixmap(QtGui.QPixmap("Resources/about.png"))
        self.aboutbg.setObjectName("aboutbg")
        self.label = QtWidgets.QLabel(about)
        self.label.setGeometry(QtCore.QRect(114, 50, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:0, stop:0 rgba(170, 85, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(about)
        self.label_2.setGeometry(QtCore.QRect(30, 110, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:0, stop:0 rgba(170, 85, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(about)
        self.label_3.setGeometry(QtCore.QRect(30, 160, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:0, stop:0 rgba(170, 85, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(about)
        self.label_4.setGeometry(QtCore.QRect(30, 210, 351, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:0, stop:0 rgba(170, 85, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(about)
        self.label_5.setGeometry(QtCore.QRect(30, 190, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:0, stop:0 rgba(170, 85, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label_5.setObjectName("label_5")

        self.retranslateUi(about)
        QtCore.QMetaObject.connectSlotsByName(about)

    def retranslateUi(self, about):
        _translate = QtCore.QCoreApplication.translate
        about.setWindowTitle(_translate("about", "Dialog"))
        self.label.setText(_translate("about", "About"))
        self.label_2.setText(_translate("about", "Ankit Sengar"))
        self.label_3.setText(_translate("about", "1819210055"))
        self.label_4.setText(_translate("about", "Mini Project:Travel Agency Management"))
        self.label_5.setText(_translate("about", "3rd Year Sec B"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    about = QtWidgets.QDialog()
    ui = Ui_about()
    ui.setupUi(about)
    about.show()
    sys.exit(app.exec_())
