# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'billing_panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_billing(object):
    def setupUi(self, billing):
        billing.setObjectName("billing")
        billing.resize(860, 464)
        billing.setMinimumSize(QtCore.QSize(860, 0))
        billing.setMaximumSize(QtCore.QSize(860, 16777215))
        self.label = QtWidgets.QLabel(billing)
        self.label.setGeometry(QtCore.QRect(-10, -20, 881, 501))
        self.label.setMinimumSize(QtCore.QSize(881, 0))
        self.label.setMaximumSize(QtCore.QSize(881, 16777215))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Resources/biiling_bg.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(billing)
        self.label_2.setGeometry(QtCore.QRect(190, 10, 181, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(36)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:1 rgba(255, 0, 0, 255));")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(billing)
        self.label_3.setGeometry(QtCore.QRect(40, 110, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:1 rgba(255, 0, 0, 255));")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(billing)
        self.label_4.setGeometry(QtCore.QRect(80, 160, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:1 rgba(255, 0, 0, 255));")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(billing)
        self.label_5.setGeometry(QtCore.QRect(10, 210, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:1 rgba(255, 0, 0, 255));")
        self.label_5.setObjectName("label_5")
        self.bil_name = QtWidgets.QLineEdit(billing)
        self.bil_name.setGeometry(QtCore.QRect(180, 110, 151, 31))
        self.bil_name.setObjectName("bil_name")
        self.bil_amount = QtWidgets.QLineEdit(billing)
        self.bil_amount.setGeometry(QtCore.QRect(180, 160, 151, 31))
        self.bil_amount.setObjectName("bil_amount")
        self.bil_mode = QtWidgets.QComboBox(billing)
        self.bil_mode.setGeometry(QtCore.QRect(180, 210, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.bil_mode.setFont(font)
        self.bil_mode.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:1 rgba(255, 0, 0, 255));\n"
"color: rgb(255, 0, 0);\n"
"border:2px solid red;")
        self.bil_mode.setObjectName("bil_mode")
        self.bil_mode.addItem("")
        self.bil_mode.addItem("")
        self.bil_mode.addItem("")
        self.bil_pay = QtWidgets.QPushButton(billing)
        self.bil_pay.setGeometry(QtCore.QRect(130, 290, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.bil_pay.setFont(font)
        self.bil_pay.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bil_pay.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:1 rgba(255, 0, 0, 255));\n"
"border:3px solid red;")
        self.bil_pay.setObjectName("bil_pay")
        self.bil_action1 = QtWidgets.QLineEdit(billing)
        self.bil_action1.setGeometry(QtCore.QRect(132, 360, 161, 22))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.bil_action1.setFont(font)
        self.bil_action1.setStyleSheet("color: rgb(255, 0, 0);\n"
"border:1px;")
        self.bil_action1.setReadOnly(True)
        self.bil_action1.setObjectName("bil_action1")
        self.bil_action2 = QtWidgets.QLineEdit(billing)
        self.bil_action2.setGeometry(QtCore.QRect(52, 400, 321, 22))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.bil_action2.setFont(font)
        self.bil_action2.setStyleSheet("color: rgb(255, 0, 0);\n"
"border:1px;")
        self.bil_action2.setReadOnly(True)
        self.bil_action2.setObjectName("bil_action2")

        self.bil_pay.clicked.connect(self.payment)

        self.retranslateUi(billing)
        QtCore.QMetaObject.connectSlotsByName(billing)

    def retranslateUi(self, billing):
        _translate = QtCore.QCoreApplication.translate
        billing.setWindowTitle(_translate("billing", "Dialog"))
        self.label_2.setText(_translate("billing", "Billing"))
        self.label_3.setText(_translate("billing", "Booking ID:"))
        self.label_4.setText(_translate("billing", "Amount:"))
        self.label_5.setText(_translate("billing", "Payment Mode:"))
        self.bil_mode.setItemText(0, _translate("billing", "UPI"))
        self.bil_mode.setItemText(1, _translate("billing", "Cash"))
        self.bil_mode.setItemText(2, _translate("billing", "Card"))
        self.bil_pay.setText(_translate("billing", "Pay"))

    def payment(self,text):

        import sqlite3
        conn = sqlite3.connect('Resources/DataFiles/booking_data.db')
        curconn=conn.cursor()

        cons_id=self.bil_name.text()
        cons_amount=self.bil_amount.text()
        cons_mode=self.bil_mode.currentText()

        if(cons_id=="" or cons_amount==""):
            self.bil_action2.setText("Fill all enteries carefully!!")
            self.bil_name.setText("")
            self.bill_amount.setText("")
        else:
            entities=(cons_id,cons_amount,cons_mode)
            curconn.execute('''INSERT INTO payment(booking_id,amount,mode)VALUES(?,?,?)''',entities)
            conn.commit()
            curconn.close()
            
        self.bil_action1.setText("Done!!")
        
        self.bil_name.setText("")
        self.bil_amount.setText("")
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    billing = QtWidgets.QDialog()
    ui = Ui_billing()
    ui.setupUi(billing)
    billing.show()
    sys.exit(app.exec_())
