# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'booking_panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_booking(object):
    def setupUi(self, booking):
        booking.setObjectName("booking")
        booking.resize(1099, 806)
        booking.setMinimumSize(QtCore.QSize(1099, 0))
        booking.setMaximumSize(QtCore.QSize(1099, 16777215))
        self.label = QtWidgets.QLabel(booking)
        self.label.setGeometry(QtCore.QRect(-80, 0, 1301, 811))
        self.label.setMinimumSize(QtCore.QSize(1301, 0))
        self.label.setMaximumSize(QtCore.QSize(1301, 16777215))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Resources/booking_bg.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(booking)
        self.label_2.setGeometry(QtCore.QRect(390, 10, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(36)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:1 rgba(255, 0, 0, 255));")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(booking)
        self.label_3.setGeometry(QtCore.QRect(440, 60, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:1 rgba(255, 0, 0, 255));")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(booking)
        self.label_4.setGeometry(QtCore.QRect(710, 200, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(22)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:1 rgba(255, 0, 0, 255));")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(booking)
        self.label_5.setGeometry(QtCore.QRect(10, 110, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(24)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:1 rgba(255, 0, 0, 255));")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(booking)
        self.label_6.setGeometry(QtCore.QRect(20, 160, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:1 rgba(255, 0, 0, 255));")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(booking)
        self.label_7.setGeometry(QtCore.QRect(10, 430, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:1 rgba(255, 0, 0, 255));")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(booking)
        self.label_8.setGeometry(QtCore.QRect(20, 460, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:1 rgba(255, 0, 0, 255));")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(booking)
        self.label_9.setGeometry(QtCore.QRect(40, 530, 55, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:1 rgba(255, 0, 0, 255));")
        self.label_9.setObjectName("label_9")
        self.bp_name = QtWidgets.QLineEdit(booking)
        self.bp_name.setGeometry(QtCore.QRect(110, 170, 241, 31))
        self.bp_name.setObjectName("bp_name")
        self.bp_car = QtWidgets.QLineEdit(booking)
        self.bp_car.setGeometry(QtCore.QRect(110, 430, 241, 31))
        self.bp_car.setObjectName("bp_car")
        self.bp_from = QtWidgets.QLineEdit(booking)
        self.bp_from.setGeometry(QtCore.QRect(110, 480, 241, 31))
        self.bp_from.setObjectName("bp_from")
        self.bp_to = QtWidgets.QLineEdit(booking)
        self.bp_to.setGeometry(QtCore.QRect(110, 530, 241, 31))
        self.bp_to.setObjectName("bp_to")
        self.bp_push_book = QtWidgets.QPushButton(booking)
        self.bp_push_book.setGeometry(QtCore.QRect(130, 590, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.bp_push_book.setFont(font)
        self.bp_push_book.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bp_push_book.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:1 rgba(255, 0, 0, 255));\n"
"border:3px solid red")
        self.bp_push_book.setObjectName("bp_push_book")
        self.bp_car1 = QtWidgets.QLineEdit(booking)
        self.bp_car1.setGeometry(QtCore.QRect(540, 360, 113, 22))
        self.bp_car1.setReadOnly(True)
        self.bp_car1.setObjectName("bp_car1")
        self.bp_car2 = QtWidgets.QLineEdit(booking)
        self.bp_car2.setGeometry(QtCore.QRect(900, 360, 113, 22))
        self.bp_car2.setReadOnly(True)
        self.bp_car2.setObjectName("bp_car2")
        self.bp_car3 = QtWidgets.QLineEdit(booking)
        self.bp_car3.setGeometry(QtCore.QRect(530, 530, 113, 22))
        self.bp_car3.setReadOnly(True)
        self.bp_car3.setObjectName("bp_car3")
        self.bp_car4 = QtWidgets.QLineEdit(booking)
        self.bp_car4.setGeometry(QtCore.QRect(900, 530, 113, 22))
        self.bp_car4.setReadOnly(True)
        self.bp_car4.setObjectName("bp_car4")
        self.bp_car5 = QtWidgets.QLineEdit(booking)
        self.bp_car5.setGeometry(QtCore.QRect(530, 690, 113, 22))
        self.bp_car5.setReadOnly(True)
        self.bp_car5.setObjectName("bp_car5")
        self.bp_car6 = QtWidgets.QLineEdit(booking)
        self.bp_car6.setGeometry(QtCore.QRect(900, 690, 113, 22))
        self.bp_car6.setReadOnly(True)
        self.bp_car6.setObjectName("bp_car6")
        self.bp_action1 = QtWidgets.QLineEdit(booking)
        self.bp_action1.setGeometry(QtCore.QRect(120, 660, 201, 22))
        self.bp_action1.setStyleSheet("border:1 px;")
        self.bp_action1.setReadOnly(True)
        self.bp_action1.setObjectName("bp_action1")
        self.label_10 = QtWidgets.QLabel(booking)
        self.label_10.setGeometry(QtCore.QRect(10, 210, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:1 rgba(255, 0, 0, 255));")
        self.label_10.setObjectName("label_10")
        self.bp_contact = QtWidgets.QLineEdit(booking)
        self.bp_contact.setGeometry(QtCore.QRect(110, 220, 241, 31))
        self.bp_contact.setText("")
        self.bp_contact.setObjectName("bp_contact")
        self.label_11 = QtWidgets.QLabel(booking)
        self.label_11.setGeometry(QtCore.QRect(10, 350, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:1 rgba(255, 0, 0, 255));")
        self.label_11.setObjectName("label_11")
        self.bp_address = QtWidgets.QLineEdit(booking)
        self.bp_address.setGeometry(QtCore.QRect(110, 350, 241, 71))
        self.bp_address.setObjectName("bp_address")
        self.label_12 = QtWidgets.QLabel(booking)
        self.label_12.setGeometry(QtCore.QRect(20, 300, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:1 rgba(255, 0, 0, 255));")
        self.label_12.setObjectName("label_12")
        self.bp_email = QtWidgets.QLineEdit(booking)
        self.bp_email.setGeometry(QtCore.QRect(110, 310, 241, 31))
        self.bp_email.setObjectName("bp_email")
        self.label_13 = QtWidgets.QLabel(booking)
        self.label_13.setGeometry(QtCore.QRect(40, 710, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:1 rgba(255, 0, 0, 255));")
        self.label_13.setObjectName("label_13")
        self.bp_bID = QtWidgets.QLineEdit(booking)
        self.bp_bID.setGeometry(QtCore.QRect(180, 710, 113, 31))
        self.bp_bID.setReadOnly(True)
        self.bp_bID.setObjectName("bp_bID")
        self.label_14 = QtWidgets.QLabel(booking)
        self.label_14.setGeometry(QtCore.QRect(30, 260, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:1 rgba(255, 0, 0, 255));")
        self.label_14.setObjectName("label_14")
        self.bp_date = QtWidgets.QLineEdit(booking)
        self.bp_date.setGeometry(QtCore.QRect(110, 260, 241, 31))
        self.bp_date.setObjectName("bp_date")

        self.bp_push_book.clicked.connect(self.booking_func)

        self.retranslateUi(booking)
        QtCore.QMetaObject.connectSlotsByName(booking)

        import json

        filename = 'Resources/DataFiles/car.json'
        with open(filename,'r') as f:
            data=json.load(f)
            self.bp_car1.setText(data["1"])
            self.bp_car1.setStyleSheet("color: rgb(255, 0, 0);")
            self.bp_car2.setText(data["2"])
            self.bp_car2.setStyleSheet("color: rgb(255, 0, 0);")
            self.bp_car3.setText(data["3"])
            self.bp_car3.setStyleSheet("color: rgb(255, 0, 0);")
            self.bp_car4.setText(data["4"])
            self.bp_car4.setStyleSheet("color: rgb(255, 0, 0);")
            self.bp_car5.setText(data["5"])
            self.bp_car5.setStyleSheet("color: rgb(255, 0, 0);")
            self.bp_car6.setText(data["6"])
            self.bp_car6.setStyleSheet("color: rgb(255, 0, 0);")
        f.close()

    def retranslateUi(self, booking):
        _translate = QtCore.QCoreApplication.translate
        booking.setWindowTitle(_translate("booking", "Dialog"))
        self.label_2.setText(_translate("booking", "BOOKING"))
        self.label_3.setText(_translate("booking", "PANEL"))
        self.label_4.setText(_translate("booking", "Cars"))
        self.label_5.setText(_translate("booking", "Details:"))
        self.label_6.setText(_translate("booking", "Name:"))
        self.label_7.setText(_translate("booking", "Car(1-6):"))
        self.label_8.setText(_translate("booking", "From:"))
        self.label_9.setText(_translate("booking", "To:"))
        self.bp_push_book.setText(_translate("booking", "BOOK"))
        self.label_10.setText(_translate("booking", "Contact:"))
        self.label_11.setText(_translate("booking", "Address:"))
        self.label_12.setText(_translate("booking", "Email:"))
        self.label_13.setText(_translate("booking", "Booking ID:"))
        self.label_14.setText(_translate("booking", "Date:"))

    def booking_func(self,text):
        import json
        from datetime import date
        import sqlite3
        conn = sqlite3.connect('Resources/DataFiles/booking_data.db')
        curconn=conn.cursor()
        
        cons_name=self.bp_name.text()
        cons_contact=self.bp_contact.text()
        cons_date=self.bp_date.text()
        cons_email=self.bp_email.text()
        cons_address=self.bp_address.text()
        cons_car=self.bp_car.text()
        cons_from=self.bp_from.text()
        cons_to=self.bp_to.text()
        today = date.today()
        
        if(cons_name==" " or cons_contact==" " or
           cons_address==" " or cons_car==" " or cons_from=="" or cons_to==" "):
            warning="Fill all the entry!!"
            self.bp_action2.setStyleSheet("color: rgb(255, 0, 0);")
            self.bp_action2.setText(warning)
            cons_name==""
            cons_contact==""
            cons_date=""
            cons_email=""
            cons_address==""
            cons_car==""
            cons_from==""
            cons_to==""
            
        else:
            entities=(cons_name,cons_contact,cons_date,cons_email,cons_address,cons_car,cons_from,cons_to,today)
            curconn.execute('''INSERT INTO booking(consumer_name,contact,send_date,email,address,car,loc_from,loc_to,date_booking)VALUES(?,?,?,?,?,?,?,?,?)''',entities)
            conn.commit()
            curconn.close()
            
        self.bp_action1.setText("Done!!")

        filename = 'Resources/DataFiles/car.json'
        with open(filename, 'r') as f:
            data = json.load(f)
            data[cons_car] = "Booked"
        f.close()

        with open(filename, 'w') as f:
            json.dump(data,f)
        f.close()

        filename = 'Resources/DataFiles/BID.json'
        with open(filename, 'r') as f:
            data = json.load(f)
            self.bp_bID.setText(data['bID'])
            num_bID = int(data['bID'])
            import smtplib 
  
            # creates SMTP session 
            s = smtplib.SMTP('smtp.gmail.com', 587) 
  
            # start TLS for security 
            s.starttls() 
  
            # Authentication 
            s.login("youremail@gmail.com", "Password") 
  
            # message to be sent 
            message = "Dear {}.\nYour car booking has been done with booking ID: {} and car no.: {}.".format(cons_name,num_bID,cons_car)
  
            # sending the mail 
            s.sendmail("youremail@gmail.com", "{}".format(cons_email), message) 
  
            # terminating the session 
            s.quit() 
            num_bID=num_bID+1
            data['bID']=str(num_bID)
        f.close()

        with open(filename, 'w') as f:
            json.dump(data,f)
        f.close()
        
        self.bp_action1.setStyleSheet("border: 0 px;")
        self.bp_action1.setStyleSheet("color: rgb(255, 0, 0);")
        self.bp_name.setText("")
        self.bp_contact.setText("")
        self.bp_address.setText("")
        self.bp_car.setText("")
        self.bp_from.setText("")
        self.bp_to.setText("")
        self.bp_date.setText("")
        self.bp_email.setText("")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    booking = QtWidgets.QDialog()
    ui = Ui_booking()
    ui.setupUi(booking)
    booking.show()
    sys.exit(app.exec_())
