# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'booking_alert.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_booking_alert(object):
    def setupUi(self, booking_alert):
        booking_alert.setObjectName("booking_alert")
        booking_alert.resize(552, 407)
        booking_alert.setMinimumSize(QtCore.QSize(552, 407))
        booking_alert.setMaximumSize(QtCore.QSize(552, 407))
        self.label = QtWidgets.QLabel(booking_alert)
        self.label.setGeometry(QtCore.QRect(-10, -60, 911, 801))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Resources/blank.png"))
        self.label.setObjectName("label")
        self.list = QtWidgets.QTableWidget(booking_alert)
        self.list.setGeometry(QtCore.QRect(10, 140, 531, 221))
        self.list.setMinimumSize(QtCore.QSize(531, 221))
        self.list.setMaximumSize(QtCore.QSize(531, 221))
        self.list.setRowCount(6)
        self.list.setColumnCount(5)
        self.list.setObjectName("list")
        self.label_2 = QtWidgets.QLabel(booking_alert)
        self.label_2.setGeometry(QtCore.QRect(174, 20, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(26)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:1 rgba(255, 0, 0, 255));")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(booking_alert)
        self.label_3.setGeometry(QtCore.QRect(70, 120, 55, 16))
        self.label_3.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:1 rgba(255, 0, 0, 255));")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(booking_alert)
        self.label_4.setGeometry(QtCore.QRect(170, 120, 55, 16))
        self.label_4.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:1 rgba(255, 0, 0, 255));")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(booking_alert)
        self.label_5.setGeometry(QtCore.QRect(250, 120, 55, 16))
        self.label_5.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:1 rgba(255, 0, 0, 255));")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(booking_alert)
        self.label_6.setGeometry(QtCore.QRect(360, 120, 55, 16))
        self.label_6.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:1 rgba(255, 0, 0, 255));")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(booking_alert)
        self.label_7.setGeometry(QtCore.QRect(470, 120, 55, 16))
        self.label_7.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:1 rgba(255, 0, 0, 255));")
        self.label_7.setObjectName("label_7")

        import sqlite3
        from datetime import date

        today=str(date.today())
        connection=sqlite3.connect('Resources/DataFiles/booking_data.db')
        result=connection.execute('''SELECT id,consumer_name,contact,address,car FROM booking WHERE send_date= '{}' '''.format(today))
        self.list.setRowCount(0)
        for row_number,row_data in enumerate(result):
            self.list.insertRow(row_number)
            for column_number,data in enumerate(row_data):
                self.list.setItem(row_number,column_number,QtWidgets.QTableWidgetItem(str(data)))
        connection.close()

        self.retranslateUi(booking_alert)
        QtCore.QMetaObject.connectSlotsByName(booking_alert)

    def retranslateUi(self, booking_alert):
        _translate = QtCore.QCoreApplication.translate
        booking_alert.setWindowTitle(_translate("booking_alert", "Dialog"))
        self.label_2.setText(_translate("booking_alert", "Booking Alert"))
        self.label_3.setText(_translate("booking_alert", "ID"))
        self.label_4.setText(_translate("booking_alert", "NAME"))
        self.label_5.setText(_translate("booking_alert", "CONTACT"))
        self.label_6.setText(_translate("booking_alert", "ADDRESS"))
        self.label_7.setText(_translate("booking_alert", "CAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    booking_alert = QtWidgets.QDialog()
    ui = Ui_booking_alert()
    ui.setupUi(booking_alert)
    booking_alert.show()
    sys.exit(app.exec_())
