# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'service_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_service_dialog(object):
    def setupUi(self, service_dialog):
        service_dialog.setObjectName("service_dialog")
        service_dialog.resize(433, 386)
        service_dialog.setMinimumSize(QtCore.QSize(433, 386))
        service_dialog.setMaximumSize(QtCore.QSize(433, 386))
        self.label = QtWidgets.QLabel(service_dialog)
        self.label.setGeometry(QtCore.QRect(0, -20, 651, 561))
        self.label.setMinimumSize(QtCore.QSize(651, 561))
        self.label.setMaximumSize(QtCore.QSize(651, 561))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Resources/service_info.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(service_dialog)
        self.label_2.setGeometry(QtCore.QRect(90, 10, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(26)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:1 rgba(255, 0, 0, 255));")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(service_dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:1 rgba(255, 0, 0, 255));")
        self.label_3.setObjectName("label_3")
        self.car_no = QtWidgets.QLineEdit(service_dialog)
        self.car_no.setGeometry(QtCore.QRect(170, 110, 113, 31))
        self.car_no.setObjectName("car_no")
        self.label_4 = QtWidgets.QLabel(service_dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 180, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:1 rgba(255, 0, 0, 255));")
        self.label_4.setObjectName("label_4")
        self.service_date = QtWidgets.QLineEdit(service_dialog)
        self.service_date.setGeometry(QtCore.QRect(170, 180, 161, 31))
        self.service_date.setObjectName("service_date")
        self.service_button = QtWidgets.QPushButton(service_dialog)
        self.service_button.setGeometry(QtCore.QRect(130, 237, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.service_button.setFont(font)
        self.service_button.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:1 rgba(255, 0, 0, 255));\n"
"border:3px solid red;")
        self.service_button.setObjectName("service_button")
        self.lineEdit = QtWidgets.QLineEdit(service_dialog)
        self.lineEdit.setGeometry(QtCore.QRect(112, 300, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:1 rgba(255, 0, 0, 255));")
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.label_5 = QtWidgets.QLabel(service_dialog)
        self.label_5.setGeometry(QtCore.QRect(14, 210, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:1 rgba(255, 0, 0, 255));")
        self.label_5.setObjectName("label_5")

        self.service_button.clicked.connect(self.service_info)

        self.retranslateUi(service_dialog)
        QtCore.QMetaObject.connectSlotsByName(service_dialog)

    def retranslateUi(self, service_dialog):
        _translate = QtCore.QCoreApplication.translate
        service_dialog.setWindowTitle(_translate("service_dialog", "Dialog"))
        self.label_2.setText(_translate("service_dialog", "Service Info"))
        self.label_3.setText(_translate("service_dialog", "Car No.(1-6):"))
        self.label_4.setText(_translate("service_dialog", "Service Date:"))
        self.service_button.setText(_translate("service_dialog", "Submit"))
        self.label_5.setText(_translate("service_dialog", "(YYYY-MM-DD)"))

    def service_info(self,text):
        import json

        car_num=self.car_no.text()
        service=self.service_date.text()
        
        filename = 'Resources/DataFiles/service.json'
        with open(filename, 'r') as f:
            data = json.load(f)
            data[car_num] = service
            self.lineEdit.setText("Submitted!!")
            self.car_no.setText(" ")
            self.service_date.setText(" ")
        f.close()

        with open(filename, 'w') as f:
            json.dump(data,f)
        f.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    service_dialog = QtWidgets.QDialog()
    ui = Ui_service_dialog()
    ui.setupUi(service_dialog)
    service_dialog.show()
    sys.exit(app.exec_())
